log4j.rootLogger=debug,std

log4j.appender.std=org.apache.log4j.ConsoleAppender
log4j.appender.std.Target=System.out
log4j.appender.std.layout=org.apache.log4j.PatternLayout
#log4j.appender.std.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] %p [%c - %M:%L]
log4j.appender.std.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] %5p %c{1}:%L - %m%n

log4j.logger.com.quart.test=DEBUG